aconv-chans: 4
aconv-filts: 3
adim: 32
atype: location
batch-size: 2
dlayers: 1
dunits: 30
elayers: 2
epochs: 3
eprojs: 32
etype: blstmp
eunits: 32
maxlen-in: 800
maxlen-out: 150
mtlalpha: 0.5
opt: adadelta
patience: 2
sampling-probability: 0.0
sortagrad: 0
subsample: '1_2_2_1_1'
train-dtype: float64
